name: Generate README

on:
  workflow_dispatch:  # Manual trigger only
  
# Add permissions needed for commits and PRs
permissions:
  contents: write
  pull-requests: write
      
jobs:
  generate-readme:
    runs-on: ubuntu-latest
    environment:
      name: Default
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for better analysis
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openai
          
      - name: Generate README
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          echo "Checking for OpenAI API key..."
          if [ -z "$OPENAI_API_KEY" ]; then
            echo "::error::OPENAI_API_KEY is not set. Please add it as a repository secret."
            exit 1
          fi
          echo "API key found. Generating README..."
          python .github/scripts/generate_readme.py
          
      - name: Check for changes
        id: git-check
        run: |
          git diff --exit-code README.md || echo "changes=true" >> $GITHUB_OUTPUT
          
      # OPTION 1: Use only create-pull-request action (recommended)
      - name: Create Pull Request
        if: steps.git-check.outputs.changes == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.PAT }}
          commit-message: Auto-update README
          title: "Auto-update README"
          body: |
            This PR updates the README.md file with auto-generated content.
            
            The content was generated based on repository analysis.
          branch: update-readme-${{ github.run_id }}
          base: ${{ github.ref }}
          
      # OPTION 2: Alternative approach (use only if option 1 doesn't work)
      # - name: Commit and push if README changed (alternative)
      #   if: steps.git-check.outputs.changes == 'true'
      #   run: |
      #     # Configure git
      #     git config --local user.email "action@github.com"
      #     git config --local user.name "GitHub Action"
      #     
      #     # Create a new branch
      #     git checkout -b update-readme-${{ github.run_id }}
      #     
      #     # Commit changes
      #     git add README.md
      #     git commit -m "Auto-update README [skip ci]"
      #     
      #     # Push using GITHUB_TOKEN
      #     git push --set-upstream origin update-readme-${{ github.run_id }}
      #     
      #     # Create PR using GitHub CLI (you'll need to add gh auth)
      #     gh pr create --title "Auto-update README" \
      #       --body "This PR updates the README.md file with auto-generated content." \
      #       --base ${{ github.ref_name }}
